version: 2.1

jobs:
  test:
    parallelism: 2
    steps:
      - checkout
      - attach_workspace:
          at: ~/rorlee
      # - run: bundle --path vendor/bundle
      - run: yarn install
      
      # Wait for DB containers to be ready
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      
      # Copy database config
      - run: cp config/database.yml.example config/database.yml

      # Setup the environment
      - run: cp .env.example .env

      # Setup the database
      - run: bin/rails db:create db:migrate

      # Run tests
      - run:
          name: Run tests
          command: |
            TEST_FILES="$(circleci tests glob "test/**/*_test.rb" | circleci tests split --split-by=timings)"
            bin/rails test $TEST_FILES

workflows:
  version: 2
  build-and-test:
    jobs:
      - test
