version: 2.1

jobs:
  test:
    parallelism: 2
    docker:
      - image: circleci/ruby:2.7.4-node-browsers
    steps:
      - checkout
      - attach_workspace:
          at: ~/rorlee
      - run: yarn install
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: cp config/database.yml.example config/database.yml
      - run: cp .env.example .env
      - run: bundle exec rails db:create db:migrate
      - run:
          name: Run tests
          command: |
            TEST_FILES=$(circleci tests glob "test/**/*_test.rb" | circleci tests split --split-by=timings)
            bundle exec rails test $TEST_FILES

workflows:
  version: 2
  build-and-test:
    jobs:
      - test
